# Generated by Django 3.2.9 on 2021-11-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='url',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='class',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, to='classroom.Student'),
        ),
    ]
