# Generated by Django 3.2.9 on 2021-11-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_subject_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
